// Auto-generated by build_secrets.py — do not edit by hand.
// AES-GCM ciphertext keyed off SITE_PASSWORD via PBKDF2-SHA256.
// Safe to publish: without the password, neither the API key, the
// proxy URL, nor the WebDAV credentials can be recovered.
window.__ZOTERO_ENC = {
  salt: "7H4qxpmZ/6PoDhS3wAJ6zQ==",
  nonce: "VGBnHsoLrvUwTPmP",
  ciphertext: "LDFUQlFO0nHDN5facoYibSFVB7jNzHsYhdADe+qQzdL6osYRluOtxEypXcd2JAG+p1Ti8BcItrs5xhTaeJkGovzSlzg6Pm8DDiY6zEPI5PcPEma165ZcoZfS9bEtufqxnQ855X1RjGvcM9Bzok9dV8CaAtyRbRng97G9j+gwolv9D1zf3833gfItAVd6Tb3Ui2taKuObGMgmxrjooO8U1W99fu6OCnHCa57f6QbVF9PO19tB7cs8N2oxXw9d2n87LeJ1oNLgpe3CYLVA8Hb+jN3FWjFCOOqBanTuctkTX8VkwQNUL+6HHzka6+f9lCOwAQk=",
  iterations: 600000
};
